FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY java-service/pom.xml .
COPY java-service/src ./src
RUN apk add --no-cache maven
RUN mvn clean package -DskipTests
EXPOSE 8001
CMD ["java", "-jar", "target/java-service-1.0.0.jar"]